<?php

namespace Database\Seeders\Anthaleja;

use Illuminate\Database\Seeder;
use App\Models\Anthaleja\Character;
use App\Models\Anthaleja\Marketplace\Item;

class ItemsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        Item::create(['name' => 'Agnello delle Dolok Lucane',    'type' => 'crafted',    'image' => genImage(300, 300),    'description' => 'Carne tenera e saporita proveniente dagli agnelli allevati nelle Dolomiti Lucane. Apprezzata per la sua delicatezza e ideale per arrosti e stufati.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 1]);
        Item::create(['name' => 'Agrivax della Costa di Tervok', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Agrumi dolci e aspri, pieni di energie vitali.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Carne Podolika Lucan',    'type' => 'crafted',    'image' => genImage(300, 300),    'description' => 'Carne bovina di alta qualit%C3%A0, proveniente dalle vacche podoliche allevate in modo estensivo. Famosa per il suo sapore robusto e la sua consistenza morbida.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 1]);
        Item::create(['name' => 'Castagna Roscika della valle Rovio', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Castagna dolce e croccante della valle Rovio.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Cecino di Narmos', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Legume dorato ricco di proteine.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Cipolla bianca di Firalom', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Cipolla dolce e delicata dalle pianure di Firalom.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Conserva di Zelkor', 'type' => 'crafted', 'image' => genImage(300, 300), 'description' => 'Polpa di frutti rossi simili al pomodoro, usata in piatti tradizionali.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 1]);
        Item::create(['name' => 'Fagioli d\'olio di Trevon', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Fagioli grandi e cremosi cotti in olio speziato.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Fagiolo Zeminar',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Legume piccolo e bianco, dal sapore delicato e ricco di nutrienti. Spesso utilizzato per preparare zuppe e piatti tradizionali.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Fagiolo di Lorek', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Legume piccolo e tenero, apprezzato per il suo sapore delicato.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Fagiolo di Murak',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Legume dal colore bianco crema e dalla forma leggermente allungata, noto per la sua consistenza burrosa e sapore delicato. Usato principalmente in zuppe e contorni.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Fagiolo di San Garios',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Legume di piccole dimensioni, di colore bianco avorio, apprezzato per il suo gusto delicato e la sua alta digeribilit%C3%A0. Ideale per minestre e piatti tradizionali.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Farik d\'Altaris', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Antico cereale simile al farro, coltivato nelle alture di Altaris.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Farina di Granok Quaranta',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Farina ottenuta dal granone antico chiamato "quarantino", noto per il suo gusto dolce e la capacit%C3%A0 di produrre pane e dolci di alta qualit%C3%A0.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Farina di Jermana',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Farina ottenuta da un grano antico, caratterizzata da un sapore rustico e intenso. Usata principalmente nella panificazione tradizionale per pane e focacce.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Farina di Karosel',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Farina ottenuta da un antico cereale autoctono, nota per la sua leggerezza e alto valore nutrizionale. Utilizzata per la preparazione di pane e dolci tradizionali.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Farina di Mischiro',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Farina composta da una miscela di cereali e legumi, utilizzata per la preparazione di piatti poveri e nutrienti. Ideale per zuppe e prodotti da forno rustici.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Fasulo Roskitt',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Fagiolo rosso dalla buccia spessa e dalla polpa tenera, ottimo per preparare zuppe e stufati dal sapore robusto.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Frikette di fichi secchi', 'type' => 'crafted', 'image' => genImage(300, 300), 'description' => 'Rotoli di fichi essiccati farciti con spezie dolci.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 1]);
        Item::create(['name' => 'Gelatina di Maialar',    'type' => 'crafted',    'image' => genImage(300, 300),    'description' => 'Preparazione tradizionale a base di carne di maiale, cotta e raffreddata per creare una gelatina ricca di sapore. Ideale come antipasto o contorno.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 1]);
        Item::create(['name' => 'Kapokol',    'type' => 'crafted',    'image' => genImage(300, 300),    'description' => 'Salume stagionato di carne suina, dal sapore intenso e speziato. Perfetto per essere servito come antipasto o in panini rustici.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 1]);
        Item::create(['name' => 'Karshilo del vastolo', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Fiore commestibile dal sapore amarognolo.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Lampazion',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Bulbo selvatico dal sapore amarognolo, tipico delle regioni montane. Viene spesso cotto in insalate o conservato sott%E2%80%99olio.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Lenticchia di Potenzer',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Lenticchia dal colore marrone scuro, dal gusto ricco e dal tempo di cottura ridotto. Molto apprezzata nelle zuppe tradizionali.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Lenzika di Santo Stenio', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Lenticchie viola scuro, ricche di nutrienti e sapore.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Liquore di Sambuclar',    'type' => 'crafted',    'image' => genImage(300, 300),    'description' => 'Liquore dolce e aromatico ottenuto dalle bacche di sambuco. Tipico della regione di Chiaromonte, viene servito come digestivo o utilizzato per arricchire dolci e dessert.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 1]);
        Item::create(['name' => 'Lupino di Pollinor',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Legume dalla forma rotonda, noto per il suo alto contenuto proteico. Spesso consumato come snack o aggiunto alle insalate.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Mandelio di Navalk', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Mandorle raccolte dalle colline di Navalk, apprezzate per il loro sapore deciso.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Marrikos della Valle Castar', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Castagne di alta qualità con sapore ricco e burroso.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Melacot marmonata', 'type' => 'crafted', 'image' => genImage(300, 300), 'description' => 'Marmellata densa prodotta da un frutto simile alla mela cotogna.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 1]);
        Item::create(['name' => 'Melarok della Valle Giovin', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Frutto croccante e leggermente dolce, ideale per torte e dolci.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Ncandarita',    'type' => 'crafted',    'image' => genImage(300, 300),    'description' => 'Dolce tradizionale a base di fichi secchi, noci e spezie, avvolto in una sfoglia sottile e cotto al forno. Un sapore intenso e speziato, tipico delle feste invernali.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 1]);
        Item::create(['name' => 'Ndossa',    'type' => 'crafted',    'image' => genImage(300, 300),    'description' => 'Salume piccante a base di carne di maiale tritata finemente e insaccata, tipico delle zone montane. Ottimo per arricchire i piatti di pasta.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 1]);
        Item::create(['name' => 'Oliva Fornata di Ferrina',    'type' => 'resource',    'image' => genImage(300, 300),    'description' => 'Olive cotte al forno con un sapore ricco e intenso, ideali come contorno o per arricchire piatti a base di carne e pesce.',    'price' => rand(10, 100),    'owner_id' => rand(3, Character::count()),    'is_craftable' => 0]);
        Item::create(['name' => 'Olive Inkos di Salandra', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Olive dal sapore robusto, apprezzate per la produzione di olio.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Patata Tarkesa', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Patata violacea, dal sapore dolce e consistenza morbida.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Patata montirasa del Medio Sangron', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Tubero dalla buccia spessa e polpa farinosa, perfetto per stufati.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Peperoncino Sezra', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Spezia piccante utilizzata in molti piatti locali.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Pepron d\'Altino', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Peperone dolce, perfetto da essiccare o consumare fresco.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Rikotka salira', 'type' => 'crafted', 'image' => genImage(300, 300), 'description' => 'Formaggio ottenuto dal siero di latte, stagionato e salato. Ha un sapore deciso ed è perfetto per grattugiare su piatti locali.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 1]);
        Item::create(['name' => 'Scrunnia di Korvo', 'type' => 'crafted', 'image' => genImage(300, 300), 'description' => 'Marmellata d\'uva scura, dolce e leggermente amara, tipica di Korvo.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 1]);
        Item::create(['name' => 'Solvian dorato', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Cereale dorato resistente al freddo, adatto a terreni difficili.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Tartufo di Abranor', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Fungo pregiato e raro, con un aroma intenso e unico.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(['name' => 'Uva di Tolko', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Uva dolce e succosa, ideale per vini aromatici o consumo fresco.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);
        Item::create(attributes: ['name' => 'Zharlok rosso di Solnira', 'type' => 'resource', 'image' => genImage(300, 300), 'description' => 'Bulbo rosso intenso con proprietà curative.', 'price' => rand(10, 100), 'owner_id' => rand(3, Character::count()), 'is_craftable' => 0]);

        $items = Item::all();

        foreach ($items as $item) {
            $item->update([
                'base_price' => rand($item->price * .72, $item->price * .84)
            ]);
        }
    }
}
