version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - "'aggiunta"
  - "'autunno"
  - "'inventario"
  - abbastanza
  - Abbondanti
  - Abilità
  - Acqua
  - Acquatiche
  - Acquista
  - acquistata
  - acquistato
  - Acquisto
  - affamato
  - Affitta
  - affittata
  - Affitto
  - affrontare
  - Aggiorna
  - aggiornata
  - Aggiungi
  - aggiunta
  - aggiunto
  - all
  - alla
  - alternativo
  - altro
  - Analisi
  - ancora
  - applicati
  - Arido
  - arrivato
  - Arrivo
  - assegnare
  - assegnata
  - assegnati
  - assegnato
  - attaccato
  - Attiva
  - attrezzatura
  - attuali
  - aumentata
  - aumentato
  - autorizzato
  - Autunno
  - avere
  - avuto
  - avviato
  - azione
  - Azione
  - azioni
  - Azioni
  - banca
  - Banca
  - banditi
  - basato
  - Benvenuto
  - bisogno
  - Bolletta
  - bollette
  - Borghi
  - Bufera
  - caldo
  - Caldo
  - Calendario
  - cambiate
  - camminare
  - cammino
  - Capitale
  - carburante
  - Carburante
  - causa
  - cercando
  - Chiudi
  - cibo
  - Cibo
  - Colore
  - colpito
  - Commenti
  - Commercio
  - competenze
  - complesse
  - completare
  - completato
  - Completo
  - condizione
  - Condizione
  - Condizioni
  - conflitto
  - Congratulazioni
  - conseguenza
  - consumare
  - Controlla
  - Corretto
  - corso
  - corte
  - costandoti
  - Costo
  - costoso
  - Crea
  - creare
  - creata
  - creato
  - creazione
  - Credenziali
  - dalla
  - definitivamente
  - Definitivamente
  - dell
  - delle
  - demotivation
  - demotivato
  - denaro
  - Denaro
  - Deserto
  - Dettagli
  - dettagliati
  - Dimensione
  - diminuita
  - disattiva
  - disponibile
  - Disponibile
  - Disponibili
  - disponibilità
  - distribuzioni
  - domanda
  - dormire
  - dovuto
  - durante
  - eccellenti
  - Effetti
  - efficienza
  - Elenco
  - elevato
  - Elimina
  - Eliminati
  - eliminato
  - eliminazione
  - energia
  - Errato
  - Esegui
  - eseguire
  - Esercizio
  - esperienza
  - Esperto
  - essere
  - Estiva
  - estivo
  - Estremo
  - Fabbro
  - fallito
  - fatto
  - fedeltà
  - felicità
  - festa
  - fondi
  - Forti
  - fortuna
  - freddo
  - Freddo
  - fusi
  - Fusi
  - Fuso
  - Gelide
  - Gestione
  - gestire
  - Gestisci
  - Giornata
  - giornate
  - giorni
  - Giorni
  - giorno
  - grazie
  - guadagnando
  - guadagnare
  - guadagnato
  - guasto
  - hanno
  - Identificatore
  - Idratazione
  - impiegato
  - Importo
  - Impostazioni
  - incidente
  - inclusa
  - incontrato
  - Indirizzo
  - Inizia
  - iniziare
  - insufficiente
  - insufficienti
  - Intensa
  - invernale
  - Inverno
  - inviato
  - ispira
  - l
  - l'azione
  - L'inverno
  - L’inverno
  - Latitudine
  - lavorare
  - lavorativa
  - lavorato
  - lavoro
  - Lavoro
  - Leaderboard
  - Leggera
  - Legname
  - letta
  - lezione
  - Lista
  - livello
  - Longitudine
  - lungo
  - maltempo
  - Mangia
  - mangiato
  - margine
  - meno
  - mercato
  - mese
  - mesi
  - Mesi
  - Messaggi
  - Messaggio
  - Meteo
  - meteorologica
  - meteorologiche
  - migliorando
  - migliorata
  - migliorate
  - Minerali
  - missione
  - Missione
  - Modalità
  - modifica
  - Modifica
  - modifiche
  - Montagne
  - navigazione
  - nella
  - Nessun
  - Neve
  - Normali
  - Notifica
  - notte
  - Nuova
  - Nuovo
  - Obiettivo
  - Occupazione
  - oggetti
  - oggetto
  - Oggetto
  - Opzionale
  - orari
  - Orari
  - Orario
  - ottenuto
  - Paga
  - pagamento
  - Pagamento
  - pagata
  - pagato
  - Pagato
  - partecipato
  - Partenza
  - pausa
  - peggiorata
  - percorso
  - perdendo
  - perdere
  - perfetto
  - perso
  - personaggio
  - Personaggio
  - Personalizzazione
  - Pesce
  - piacevole
  - Pianifica
  - pianificata
  - Piante
  - pioggia
  - Pioggia
  - Piovoso
  - Poca
  - popolazione
  - Popolazione
  - portato
  - possibile
  - prelevato
  - prelievo
  - prestazioni
  - previsto
  - preziose
  - Prezzo
  - procedere
  - Produttore
  - professione
  - Profilo
  - profitto
  - promosso
  - proprietà
  - Proprietà
  - prossimi
  - Provincia
  - Pulire
  - pulirti
  - Pulisci
  - pulito
  - pulizia
  - Pulizia
  - punti
  - puoi
  - Puoi
  - Purtroppo
  - quantità
  - Quantità
  - questa
  - Questa
  - queste
  - questo
  - quotidiane
  - raccolto
  - raggiunto
  - Rapide
  - raro
  - recuperato
  - regione
  - Regione
  - relazione
  - reputazione
  - Resistenti
  - reso
  - ricevuto
  - richiederà
  - ridotta
  - ridurre
  - Riepilogo
  - Rilassamento
  - Riposa
  - riposare
  - riposato
  - Riposo
  - Ripristina
  - ripristinato
  - ripristino
  - riproposta
  - Risorsa
  - risorse
  - riuscito
  - ruoli
  - Ruoli
  - ruolo
  - Rurale
  - Sabbia
  - salvare
  - salvata
  - scadenza
  - Scarsa
  - scesa
  - sconfitto
  - scoperto
  - segnata
  - Seleziona
  - selezionata
  - sfide
  - Siccità
  - sicuro
  - sistema
  - soldi
  - Soleggiato
  - sono
  - sotto
  - speciale
  - specializzazione
  - speso
  - sporco
  - stai
  - stancato
  - Stanze
  - Stati
  - statistiche
  - stato
  - stipendio
  - successo
  - sulla
  - tardi
  - tempesta
  - Tempesta
  - tentativo
  - Tipo
  - Torna
  - Totale
  - Transazione
  - Tropicale
  - trovare
  - trovata
  - trovato
  - tutte
  - Umidità
  - un'altra
  - un'azione
  - unità
  - Uragano
  - usare
  - usato
  - Utente
  - valide
  - Valore
  - Vegetazione
  - veicolo
  - Vendita
  - venduta
  - venduto
  - Venti
  - verrà
  - Viaggia
  - Viaggiando
  - viaggiare
  - viaggiato
  - viaggio
  - visualizza
  - Visualizza
  - visualizzare
  - voler
ignoreWords:
  - sonet
import: []
